import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useId } from 'react';
import axios from 'axios';

export default function Home({ pokemonList }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href=''>App practica SSR</a>
        </h1>
        {pokemonList.map((pokemon) => {
          const pokeId = useId();
          return (
            <div key={pokeId + pokemon.name}>
              <p>{pokemon.name}</p>
            </div>
          );
        })}
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getServerSideProps() {
  try {
    const response = await axios.get(
      'https://pokeapi.co/api/v2/pokemon?limit=100&offset=0'
    );
    const pokemonList = await response.data.results;
    return {
      props: {
        pokemonList,
      },
    };
  } catch (error) {
    console.error('Error fetching data:', error);
    return {
      props: {
        pokemonList: [],
      },
    };
  }
}
